### ISSUE TITLE
install ICA aroma error: No matching distribution found for numpy==1.22.0

### ISSUE THREAD

**Issue by vogab** [maartenmennes/ICA-AROMA#63] opened 2023-04-04 13:58 UTC
Hi,
I would like to run ICA Aroma on my WSL. I tried to check if my python packages meet the requirements running:
python2.7 -m pip install -r requirements.txt

However, I've got the following error message:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting future
  Using cached future-0.18.3.tar.gz (840 kB)
Collecting matplotlib==2.2
  Using cached matplotlib-2.2.0-cp27-cp27mu-manylinux1_x86_64.whl (12.5 MB)
ERROR: Could not find a version that satisfies the requirement numpy==1.22.0 (from -r requirements.txt (line 3)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6)
**ERROR: No matching distribution found for numpy==1.22.0 (from -r requirements.txt (line 3))**

I tried to install numpy 1.22.0 differently, downloading it from pypi, and running this line from the uncompressed numpy directory:
python2.7 setup.py install

But I got an error too:

  File "setup.py", line 59
    raise RuntimeError(f'Cannot parse version {FULLVERSION}')
                                                           ^
SyntaxError: invalid syntax

How could I solve this?

It almost looks as if numpy 1.22.0 is not available for python 2.7 anymore...

Best,
Gabriel

**Comment by maartenmennes** [comment] 2023-04-05 08:54
closed as duplicate of #59

**Closed by maartenmennes** 2023-04-05 08:54 UTC
